"""empty message

Revision ID: 077c6efa3526
Revises: 5c81684501fa
Create Date: 2025-03-03 18:11:44.994871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '077c6efa3526'
down_revision = '5c81684501fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号码'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='id唯一值',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('userName',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               comment='密码',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_user', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
        batch_op.alter_column('userName',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='id唯一值',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
