"""empty message

Revision ID: 5c81684501fa
Revises: d8434ba45ccb
Create Date: 2025-03-03 17:32:25.393791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c81684501fa'
down_revision = 'd8434ba45ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['userName'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
